package com.liu.tohappy.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liu.tohappy.entity.SumEntity;

import com.liu.tohappy.greendao.SumEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sumEntityDaoConfig;

    private final SumEntityDao sumEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sumEntityDaoConfig = daoConfigMap.get(SumEntityDao.class).clone();
        sumEntityDaoConfig.initIdentityScope(type);

        sumEntityDao = new SumEntityDao(sumEntityDaoConfig, this);

        registerDao(SumEntity.class, sumEntityDao);
    }
    
    public void clear() {
        sumEntityDaoConfig.clearIdentityScope();
    }

    public SumEntityDao getSumEntityDao() {
        return sumEntityDao;
    }

}
